language: node_js
node_js:
  - "6.9.2"
install:
  - npm install
script:
  - npm run lint
  - npm test
notifications:
  email:
    recipients:
      - kailunyao@163.com
    on_success: never
    on_failure: always